### ISSUE TITLE
The vamp Lamia not work

### ISSUE THREAD

**Issue by wsdlll** [magneticio/vamp2setup#16]
hi, i have try the  0.1.96 realease vamp lamia and the master branch in my private cloud. And the UI say "Cluster default is not initialized", how can i fix it? 

istio:0.8.0
kubernetes:1.9

Thank you for your help :)

**Comment by avalcepina** [comment]
The 0.1.96 release included a bug, I think that's the reason why you are getting the "Cluster default is not initialized" message.
Could you please try again with master or 0.3.0 (which is actually the same at this time) and let us know what notifications you get? 
Ideally you should be getting something like "Initializing cluster default" a few times before the cluster is ready.

Istio initialization can take up to a few minutes (generally obtaining IP is the longest operation) , but after 10 - 30 seconds you should be able to use the list of resource names we provided at the start of the readme to verify the status of Istio installation. 
Could you please check if everything is being correctly created?

**Comment by wsdlll** [comment]
Thank you for your help! I have try it with master release and it has worked.

**Comment by avalcepina** [comment]
Happy to help! Let us know if you have any feedback
